In [3]:
import numpy as np

In [4]:
height = [1.73,1.68,1.71,1.89,1.79]

In [5]:
np_height = np.array(height)

In [6]:
np_height

array([ 1.73,  1.68,  1.71,  1.89,  1.79])

In [7]:
weight = [65.4,59.2,63.6,88.4,68.7]

In [8]:
np_weight = np.array(weight)

In [9]:
np_weight

array([ 65.4,  59.2,  63.6,  88.4,  68.7])

In [10]:
bmi = np_weight/np_height**2

In [11]:
bmi

array([ 21.85171573,  20.97505669,  21.75028214,  24.7473475 ,  21.44127836])